### ISSUE TITLE
mac 环境下执行react-native run-android出现UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by moshaoxia** [songxiaoliang/ComicApp#4]
➜  ComicApp git:(master) react-native run-android
JS server already running.
Running /Users/mohaiyang/Documents/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 8FS7N16715000668 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:15157) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
(node:15157) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
➜  ComicApp git:(master) 
手机是7.0的Android系统

**Comment by songxiaoliang** [comment]
查验下是否已启动gradle启动权限

**Comment by moshaoxia** [comment]
-rwxr-xr-x  1 mohaiyang  staff  5080 Feb 20 11:36 gradlew
接着又出现
* What went wrong:
Execution failed for task ':app:installDebug'.
> Failed to install on any devices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.973 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:15713) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
(node:15713) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by songxiaoliang** [comment]
目测这个问题依然是gradle编译错误，看看你修改的代码是否有错误

**Comment by moshaoxia** [comment]
只有这个类有改动
package com.comicbook;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by songxiaoliang** [comment]
恩，这个类没有什么问题的，你在根目录下执行下gradlew compileDebug --stacktrace ，跟踪一下错误记录。

**Comment by moshaoxia** [comment]
我qq345079386
➜  ComicApp git:(master) ✗ gradlew compileDebug --stacktrace
zsh: command not found: gradlew
➜  ComicApp git:(master) ✗ gradlew compileDebug --stacktrace
zsh: command not found: gradlew
➜  ComicApp git:(master) ✗ cd android 
➜  android git:(master) ✗ gradlew compileDebug --stacktrace

**Comment by moshaoxia** [comment]
对了，我要是直接安装打包出来的apk是可以正常运行的

**Comment by moshaoxia** [comment]
* Exception is:
org.gradle.execution.TaskSelectionException: Task 'compileDebug' not found in root project 'ComicApp'.
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLauncher.java:142)
        at org.gradle.internal.Factories$1.create(Factories.java:22)

**Comment by songxiaoliang** [comment]
修改一下gradle版本。看你AS gradle的版本是多少

**Comment by moshaoxia** [comment]
我修改成这样就可以跑了
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
       // classpath 'com.android.tools.build:gradle:1.2.3'
        classpath 'com.android.tools.build:gradle:1.3.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by AlphaDu** [comment]
我也有同样的问题，在mac和windows都是这个错误~

**Comment by DaDaDaDaDaBocai** [comment]
我也是这样的问题

**Comment by DaDaDaDaDaBocai** [comment]
@shaokaoxianren 请问怎么解决?

**Comment by songxiaoliang** [comment]
@AlphaDu 出现这样的问题一般都是你配置版本环境的问题，请参考上述解决。

**Comment by songxiaoliang** [comment]
@DaDaDaDaDaBocai Android下修改gradle版本，重新编译。
